WIP: Scan revamp
3DprintFIT/BI-3DT pull request #131
Opened 2018-11-09 14:06 UTC by hroncok

2018-11-10 20:57 UTC, Hanyman8 requested changes

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
>  jsou 3Dskenery v oblasti geodetického měření, digitalizace budov,
```suggestion
jsou 3D skenery v oblasti geodetického měření, digitalizace budov,
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +===== Structured light
Hodně se počešťovalo u osatatních a teď je tu tohle a Time of flight, které jsou anglicky.

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +.Poissin Reconstruction
```suggestion
.Poisson Reconstruction
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +.Načtená mehs není moc dobře vidět
```suggestion
.Načtená mesh není moc dobře vidět
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +můžeme je porovnat. Na cvičení si to ukážeme, pokud materiály čtete z domu,
```suggestion
můžeme je porovnat. Na cvičení si to ukážeme, pokud materiály čtete z domova,
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +. V _Propeties_ zvolit u obou _Colors → RGB_.
```suggestion
. V _Properties_ zvolit u obou _Colors → RGB_.
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +. V _Propeties_ zkontrolovat _Colors → Scalar field_, obsahuje napočítané
```suggestion
. V _Properties_ zkontrolovat _Colors → Scalar field_, obsahuje napočítané
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +. _Propeties → Color Scale → Visible_.
```suggestion
. _Properties → Color Scale → Visible_.
```

2018-11-10 20:57 UTC, Hanyman8 commented on tutorials/scan.adoc
> +. V _Propeties_ opět zvolit u obou _Colors → RGB_.
```suggestion
. V _Properties_ opět zvolit u obou _Colors → RGB_.
```

2018-11-10 21:10 UTC, hroncok commented on tutorials/scan.adoc
> +===== Structured light
Jo, to jsem neměnil. Máš nápad, jak to přeložit? Napsat tam strukturované světlo mi přijde divný.

2018-11-11 11:58 UTC, Hanyman8 commented on tutorials/scan.adoc
> +===== Structured light
To mně taky... Asi bych to nechal.

2018-11-11 12:00 UTC, Hanyman8 approved these changes

2018-11-11 20:12 UTC, merged