Initial ADMesh Czech text based on Edux with minor improvements
3DprintFIT/BI-3DT pull request #2
Opened 2017-09-04 15:47 UTC by hroncok

2017-09-04 16:30 UTC, syky27 requested changes
Velke N za teckou

2017-09-04 16:30 UTC, syky27 commented on cs/admesh.md
> +meshi a chybám v ní](./mesh.md). načítat a ukládat soubory ve formátu STL není
N

2017-09-04 21:02 UTC, hroncok commented
Amended.

2017-09-06 15:25 UTC, syky27 approved these changes

2017-09-06 15:26 UTC, merged